# Generated by Django 5.2.3 on 2025-08-16 18:30

import django.db.models.deletion
import theater.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-show_time']},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='showtime',
            new_name='show_time',
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to=theater.models.play_image_file_path),
        ),
        migrations.AlterField(
            model_name='performance',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='theater.play'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='theater_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='theater.theaterhall'),
        ),
        migrations.AlterField(
            model_name='play',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theater.actor'),
        ),
        migrations.AlterField(
            model_name='play',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theater.genre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theater.performance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theater.reservation'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('performance', 'row', 'seat')},
        ),
    ]
